### ISSUE TITLE
Hidden and disabled fields not sends

### ISSUE THREAD

**Issue by vetash** [Paul-Zi/paulzi-form#1]
I trying to use library in my project based on F3 framework. I have many disabled and hidden fields and i notice that fields with disabled attribute and fields with hidden class not sends.

**Comment by paulzi** [comment]
Disabled fields is not send - it is standard behavior in browsers.
Regarding hidden class need more information (please show your code).

**Comment by vetash** [comment]
Ah, it's my bad. I used bootstrap3 and I though disabled is same as readonly. Also my hidden fields contains disabled attribute. 
All works fine, sorry and thank you for attention. :smile:
